# 3-rbac-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, resources, get, */Secret, allow
    p, role:admin, exec, create, */*, allow
